# Generated by Django 4.2.6 on 2023-11-03 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asosiy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HMavsum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hozirgi_mavsum', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Hozirgi Mavsum',
                'verbose_name_plural': 'Hozirgi Mavsum',
            },
        ),
        migrations.AlterField(
            model_name='club',
            name='logo',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
